[tool.pycodestyle]
blank-after-import = 1
blank-after-class = 1
blank-before-class = 2

[tool.black]
skip-string-normalization = true
use-pycodestyle = true
line_length = 88

[tool.isort]
profile = 'black'
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
lines_after_imports = 1
extend_skip = [".git",".tox","*prod.py","*dev.py","*base.py","*__init__.py","build","tests"]

[tool.autoflake]
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true